                 #######################
                 #                     #
                 # Made By GabyFulchic #
                 #                     #
                 #     20/08/2019      #
                 #                     #
                 #######################
version: "3.7"

## Pour créer le bon network
#  ./create-network.sh

networks:
  your-network:
    external: true

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'Toto1234'
    volumes:
      - /srv/mysql/var/lib/mysql:/var/lib/mysql
    networks:
      your-network:
        ipv4_address: 172.16.33.4
        aliases:
          - mysql
          - sql
          - db
  
  elkarbackup:
    image: elkarbackup/elkarbackup:1.3.1-apache
    container_name: elkarbackup
    privileged: true
    ports:
      - 80:80
    depends_on:
      - mysql
    environment:
      SYMFONY__DATABASE__PASSWORD: 'Toto1234'
      EB_CRON: enabled
    volumes:
      - /srv/elkarbackup/var/lib/elkarbackup/.ssh:/app/.ssh
    networks:
      your-network:
        ipv4_address: 172.16.33.3
        aliases:
          - elkarbackup
          - elkar
          - eb

  eb-client:
    image: elkarbackup/client
    container_name: eb-client
    depends_on:
      - db
      - elkarbackup
    networks:
      your-network:
        ipv4_address: 172.16.33.5
        aliases:
          - elkar-client
          - eb-client
          - client
